# Generated by Django 4.0 on 2023-11-15 00:40

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, unique=True)),
                ('material_min_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('material_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Material Unit Category',
            },
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_abbv', models.CharField(max_length=20)),
                ('unit_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialunitcategory')),
            ],
            options={
                'verbose_name_plural': 'Material Units',
            },
        ),
        migrations.CreateModel(
            name='Material_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_stock_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=6, max_digits=15)),
                ('material_total_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ordered_date', models.DateField(default=django.utils.timezone.now)),
                ('order_update', models.DateTimeField(auto_now=True)),
                ('material_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.material')),
                ('owner', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='material_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.materialunit'),
        ),
    ]
