# Generated by Django 4.0 on 2023-11-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material_inventory',
            options={'verbose_name_plural': 'Material Inventories'},
        ),
    ]
