# Generated by Django 4.0 on 2024-02-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sales_sales_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_sub_total',
        ),
    ]
