# Generated by Django 4.0 on 2023-11-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_material_inventory_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='material_inventory',
            name='material_name',
        ),
    ]
