# Generated by Django 4.0 on 2024-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sales_sales_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_VAT',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
