# Generated by Django 4.0 on 2023-11-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_material_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material_min_stock',
            new_name='product_min_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_note',
            new_name='product_note',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_unit',
            new_name='product_unit',
        ),
    ]
