# Generated by Django 4.0 on 2024-02-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sales_sales_vat_sales_sales_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_VAT',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_sub_total',
        ),
    ]
