# Generated by Django 4.0 on 2023-11-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_material_min_stock_product_product_min_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material_inventory',
            old_name='material_cost',
            new_name='product_cost',
        ),
        migrations.RenameField(
            model_name='material_inventory',
            old_name='material_stock',
            new_name='product_stock',
        ),
        migrations.RenameField(
            model_name='material_inventory',
            old_name='material_stock_left',
            new_name='product_stock_left',
        ),
        migrations.RenameField(
            model_name='material_inventory',
            old_name='material_total_cost',
            new_name='product_total_cost',
        ),
        migrations.AddField(
            model_name='material_inventory',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
    ]
