# Generated by Django 4.0 on 2023-11-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_rename_material_cost_material_inventory_product_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material_Inventory',
            new_name='Product_Inventory',
        ),
    ]
