# Generated by Django 4.0 on 2024-02-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sales_customer_alter_sales_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventory',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
        migrations.AlterField(
            model_name='product_inventory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.supplier'),
        ),
    ]
