# Generated by Django 4.0 on 2023-11-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_material_inventory_product_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialUnit',
            new_name='Unit',
        ),
        migrations.RenameModel(
            old_name='MaterialUnitCategory',
            new_name='UnitCategory',
        ),
    ]
