# Generated by Django 4.0 on 2024-02-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_inventorytransaction_inventory_pk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_margin',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_total_price',
        ),
    ]
