# Generated by Django 4.0 on 2023-12-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_inventory',
            options={'verbose_name_plural': 'Product Inventories'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': 'Product Units'},
        ),
        migrations.AlterModelOptions(
            name='unitcategory',
            options={'verbose_name_plural': 'Product Unit Category'},
        ),
        migrations.AddField(
            model_name='product_inventory',
            name='inventory_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
