# Generated by Django 4.0 on 2024-02-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_sales_sales_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_margin_percent',
        ),
    ]
