# Generated by Django 4.0 on 2023-12-10 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_dr', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('sales_invoice', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('sales_date', models.DateField(default=django.utils.timezone.now)),
                ('sales_updated', models.DateTimeField(auto_now=True)),
                ('sales_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_unit_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('sales_total_price', models.DecimalField(decimal_places=6, max_digits=24)),
                ('sales_unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('sales_total_cost', models.DecimalField(decimal_places=6, max_digits=24)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
        ),
    ]
