# Generated by Django 4.0 on 2023-12-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_margin',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_margin_percent',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
