# Generated by Django 4.0 on 2024-02-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_sales_sales_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials_inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
