# Generated by Django 4.0 on 2024-03-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rawmaterials_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('MANUFACTURED', 'MANUFACTURED'), ('IMPORTED', 'IMPORTED'), ('LOCAL_PURCHASE', 'LOCAL_PURCHASE')], default='', max_length=16, null=True),
        ),
    ]
