# Generated by Django 4.0 on 2023-12-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sales_sales_margin_sales_sales_margin_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='order_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
