# Generated by Django 4.0 on 2024-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sales_tax_percent_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=12, max_digits=6, null=True),
        ),
    ]
