# Generated by Django 4.0 on 2023-12-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sales_order_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='order_update',
        ),
    ]
