# Generated by Django 4.0 on 2023-12-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_sales_order_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
