# Generated by Django 4.0 on 2024-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sales_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials_inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
