# Generated by Django 4.0 on 2023-12-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_sales_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_supplier', models.CharField(max_length=250, verbose_name='Customer/Supplier')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_inventory', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('ADD', 'ADD'), ('MINUS', 'MINUSE')], default='ADD', max_length=5)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
        ),
    ]
