# Generated by Django 4.0 on 2024-03-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_rawmaterials_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='tax_percent',
        ),
    ]
