# Generated by Django 4.0 on 2023-12-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
