# Generated by Django 4.0 on 2023-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inventorytransaction_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
