# Generated by Django 4.0 on 2024-03-02 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_salesinvoice_sales_salesinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
