# Generated by Django 4.0 on 2024-03-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_salesinvoice_created_at_salesinvoice_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
