# Generated by Django 4.0 on 2023-12-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_inventory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
    ]
