# Generated by Django 4.0 on 2023-12-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_product_inventory_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASES', 'PURCHASES'), ('SALES', 'SALES')], default='PURCHASES', max_length=10),
        ),
    ]
