# Generated by Django 4.0 on 2024-03-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_salesinvoice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['sales_invoice']},
        ),
    ]
