# Generated by Django 4.0 on 2024-03-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_salesinvoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='salesInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.salesinvoice'),
        ),
    ]
