# Generated by Django 4.0 on 2023-12-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_inventorytransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='current_inventory',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='customer_supplier',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='unit_price',
        ),
    ]
