# Generated by Django 4.0 on 2023-12-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_inventorytransaction_current_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product_inventory'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='sales_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sales'),
        ),
    ]
