# Generated by Django 4.0 on 2024-03-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_sales_salesinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.product_inventory'),
        ),
    ]
