# Generated by Django 4.0 on 2023-12-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_inventorytransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_inventory',
            old_name='product_stock',
            new_name='quantity',
        ),
    ]
