# Generated by Django 4.0 on 2023-12-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_product_stock_product_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='inventory_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_inventory'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='sales_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sales'),
        ),
    ]
