# Generated by Django 4.0 on 2023-12-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_inventorytransaction_inventory_pk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_inventory',
            options={'ordering': ['ordered_date'], 'verbose_name_plural': 'Product Inventories'},
        ),
    ]
