# Generated by Django 4.0 on 2024-03-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_inventorytransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rawmaterials_inventorytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
