# Generated by Django 4.0 on 2024-03-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rawmaterials_inventorytransaction_m_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='p_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='s_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
    ]
