# Generated by Django 4.0 on 2024-03-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_inventorytransaction_p_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_invoice',
        ),
    ]
