# Generated by Django 4.0 on 2023-12-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['sales_date'], 'verbose_name_plural': 'Sales'},
        ),
    ]
