# Generated by Django 4.0 on 2024-03-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_sales_sales_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='salesInvoice',
            new_name='sales_invoice',
        ),
    ]
