# Generated by Django 4.0 on 2024-03-10 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_salesinvoice_sales_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
