# Generated by Django 4.0 on 2023-12-18 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_product_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
