# Generated by Django 4.0 on 2024-03-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_product_inventory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
