# Generated by Django 5.0 on 2023-12-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_inventorytransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_inventory',
            name='inventory_type',
            field=models.CharField(blank=True, choices=[('MANUFACTURED', 'MANUFACTURED'), ('IMPORTED', 'IMPORTED')], default='', max_length=15, null=True),
        ),
    ]
