# Generated by Django 5.0 on 2023-12-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_product_inventory_inventory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_inventory',
            name='inventory_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('MANUFACTURED', 'MANUFACTURED'), ('IMPORTED', 'IMPORTED')], default='', max_length=15, null=True),
        ),
    ]
