# Generated by Django 4.0 on 2024-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_salesinvoice_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sample_ucost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
