# Generated by Django 5.0 on 2023-12-27 10:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_product_inventory_inventory_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, unique=True)),
                ('material_min_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_stock_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=6, max_digits=15)),
                ('material_total_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ordered_date', models.DateField(default=django.utils.timezone.now)),
                ('order_update', models.DateTimeField(auto_now=True)),
                ('material_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier')),
            ],
        ),
    ]
