# Generated by Django 4.0 on 2024-03-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sales_sample_ucost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sample_ucost',
        ),
    ]
