# Generated by Django 5.0 on 2023-12-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rawmaterials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterials',
            options={'verbose_name_plural': 'Raw Materials'},
        ),
    ]
