# Generated by Django 5.0 on 2023-12-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_rawmaterials_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterials',
            name='material_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
