# Generated by Django 4.0 on 2024-03-18 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_customer_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
