# Generated by Django 5.0 on 2023-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rawmaterials_material_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterials',
            old_name='order_update',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='material_cost',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='material_stock_left',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='material_total_cost',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
