# Generated by Django 4.0 on 2024-03-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_salesinvoice_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_status',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='', max_length=6, null=True),
        ),
    ]
