# Generated by Django 5.0 on 2023-12-28 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_order_update_rawmaterials_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_cost', models.DecimalField(decimal_places=6, max_digits=15)),
                ('product_total_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ordered_date', models.DateField(default=django.utils.timezone.now)),
                ('order_update', models.DateTimeField(auto_now=True)),
                ('inventory_note', models.TextField(blank=True, null=True)),
                ('material_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rawmaterials')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier')),
            ],
            options={
                'verbose_name_plural': 'Raw Material Inventories',
                'ordering': ['ordered_date'],
            },
        ),
    ]
