# Generated by Django 4.0 on 2024-03-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_salesinvoice_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_paid_date',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
