# Generated by Django 5.0 on 2023-12-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rawmaterials_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterials_inventory',
            old_name='product_cost',
            new_name='material_cost',
        ),
        migrations.RenameField(
            model_name='rawmaterials_inventory',
            old_name='product_stock_left',
            new_name='material_stock_left',
        ),
        migrations.RenameField(
            model_name='rawmaterials_inventory',
            old_name='product_total_cost',
            new_name='material_total_cost',
        ),
    ]
