# Generated by Django 4.0 on 2024-03-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_sales_sales_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='sales_invoice',
            field=models.CharField(blank=True, default='', max_length=150, null=True, unique=True),
        ),
    ]
