# Generated by Django 5.0 on 2023-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_product_cost_rawmaterials_inventory_material_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials_inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
