# Generated by Django 4.0 on 2024-03-18 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_salesinvoice_sales_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='sales_invoice',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
    ]
