# Generated by Django 5.0 on 2023-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_rawmaterials_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials_inventory',
            name='material_stock_left',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
