# Generated by Django 5.0 on 2023-12-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_rawmaterials_inventory_material_stock_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rawmaterials')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='api.RawMaterials_Product', to='api.rawmaterials'),
        ),
    ]
