# Generated by Django 5.0 on 2023-12-29 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rawmaterials_product_product_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials_InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('materials_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rawmaterials_inventory')),
                ('product_inventory_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_inventory')),
            ],
        ),
    ]
