# Generated by Django 4.0 on 2024-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_salesinvoice_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
