# Generated by Django 5.0 on 2023-12-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rawmaterials_inventorytransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterials_inventorytransaction',
            old_name='materials_pk',
            new_name='materials_inventory_pk',
        ),
    ]
