# Generated by Django 4.0 on 2024-05-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_salesinvoice_invoice_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_inventory',
            options={'ordering': ['ordered_date', 'created_at', 'pk'], 'verbose_name_plural': 'Product Inventories'},
        ),
    ]
