# Generated by Django 5.0 on 2023-12-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_materials_pk_rawmaterials_inventorytransaction_materials_inventory_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterials_inventorytransaction',
            options={'ordering': ['transaction_date']},
        ),
    ]
