# Generated by Django 4.0 on 2024-05-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_product_inventory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['sales_date', 'created_at', 'pk'], 'verbose_name_plural': 'Sales'},
        ),
    ]
