# Generated by Django 5.0 on 2023-12-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_rawmaterials_inventorytransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_inventory',
            name='ingredients_transaction',
            field=models.ManyToManyField(through='api.RawMaterials_InventoryTransaction', to='api.rawmaterials_inventory'),
        ),
    ]
