# Generated by Django 4.0 on 2024-05-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_rawmaterials_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials_inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
