# Generated by Django 5.0 on 2023-12-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_product_inventory_ingredients_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterials_product',
            options={'verbose_name_plural': 'Raw Material to Product Formulation'},
        ),
    ]
