# Generated by Django 5.0 on 2023-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_rawmaterials_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='', max_length=6, null=True),
        ),
    ]
