# Generated by Django 4.0 on 2024-05-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_rawmaterials_inventory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='sales_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salestrans', to='api.sales'),
        ),
    ]
