# Generated by Django 5.0 on 2024-01-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_sales_sales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
