# Generated by Django 5.0 on 2024-01-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_sales_sales_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
