# Generated by Django 4.0 on 2024-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_inventorytransaction_inventory_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_transaction',
            field=models.ManyToManyField(related_name='productinventory', through='api.InventoryTransaction', to='api.Product_Inventory'),
        ),
    ]
