# Generated by Django 5.0.6 on 2024-05-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_sales_sales_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='inventory_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.product_inventory'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='sales_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_transaction',
            field=models.ManyToManyField(through='api.InventoryTransaction', to='api.product_inventory'),
        ),
    ]
