# Generated by Django 4.0 on 2024-01-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_sales_sales_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='api.RawMaterials_Product', to='api.RawMaterials'),
        ),
        migrations.AlterField(
            model_name='product_inventory',
            name='ingredients_transaction',
            field=models.ManyToManyField(through='api.RawMaterials_InventoryTransaction', to='api.RawMaterials_Inventory'),
        ),
    ]
